version: 2
parameters:
  temp-workspace:
    type: string
    default: "/temp/workspace"
jobs:
  编译:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/circleci-demo

    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install package ${MVN_ARGS}

      - save_cache:
          paths:
            -  ~/circleci-demo/.repo
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_artifacts:
          path: target/
          destination: circleci-demo-jar

      - persist_to_workspace:
          root: << parameters.temp-workspace >>
          paths:
            - ~/circleci-demo
  测试:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: << parameters.temp-workspace >>

    environment:
      JVM_OPTS: -Xmx3200m
      MVN_ARGS: -Dmaven.repo.local=.repo

    steps:
      - attach_workspace:
          at: << parameters.temp-workspace >>

      - run: | 
          cd << parameters.temp-workspace >>
          mvn clean test ${MVN_ARGS}

      - store_test_results:
          path: target/surefire-reports


workflows:
  version: 2
  build-deploy:
    jobs:
      - 编译:

      - 测试:
          requires:
            - build

      - 确认发布:
          type: approval
          requires:
            - 测试

      - 发布至站点1:
          requires:
            - 确认发布
          filters:
            branches:
              only: master

      - 发布至站点2:
          requires:
            - 确认发布
          filters:
            branches:
              only: master
